backend: tensorflow
class_name: Sequential
config:
  layers:
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple
      - null
      - 512
      dtype: float32
      name: dense_14_input
      ragged: false
      sparse: false
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      batch_input_shape: !!python/tuple
      - null
      - 512
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
      kernel_regularizer: null
      name: dense_14
      trainable: true
      units: 256
      use_bias: true
  - class_name: Dropout
    config:
      dtype: float32
      name: dropout_10
      noise_shape: null
      rate: 0.5
      seed: null
      trainable: true
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
      kernel_regularizer: null
      name: dense_15
      trainable: true
      units: 128
      use_bias: true
  - class_name: Dropout
    config:
      dtype: float32
      name: dropout_11
      noise_shape: null
      rate: 0.5
      seed: null
      trainable: true
  - class_name: Dense
    config:
      activation: softmax
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
      kernel_regularizer: null
      name: dense_16
      trainable: true
      units: 2
      use_bias: true
  name: sequential_5
keras_version: 2.4.0
