"""empty message

Revision ID: 759cb6ffdfbe
Revises: 83005df2e9af
Create Date: 2021-03-24 13:46:07.728642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759cb6ffdfbe'
down_revision = '83005df2e9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('result_day', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'result_day')
    # ### end Alembic commands ###
