"""empty message

Revision ID: 83005df2e9af
Revises: ae57169933b6
Create Date: 2021-03-23 14:27:51.986141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83005df2e9af'
down_revision = 'ae57169933b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('reddit_average', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('reddit_lower_quartile', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('reddit_maximum', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('reddit_median', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('reddit_minimum', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('reddit_upper_quartile', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('tumblr_average', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('tumblr_lower_quartile', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('tumblr_maximum', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('tumblr_median', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('tumblr_minimum', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('tumblr_upper_quartile', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('twitter_average', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('twitter_lower_quartile', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('twitter_maximum', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('twitter_median', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('twitter_minimum', sa.Float(precision=32), nullable=True))
    op.add_column('analysis_results', sa.Column('twitter_upper_quartile', sa.Float(precision=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'twitter_upper_quartile')
    op.drop_column('analysis_results', 'twitter_minimum')
    op.drop_column('analysis_results', 'twitter_median')
    op.drop_column('analysis_results', 'twitter_maximum')
    op.drop_column('analysis_results', 'twitter_lower_quartile')
    op.drop_column('analysis_results', 'twitter_average')
    op.drop_column('analysis_results', 'tumblr_upper_quartile')
    op.drop_column('analysis_results', 'tumblr_minimum')
    op.drop_column('analysis_results', 'tumblr_median')
    op.drop_column('analysis_results', 'tumblr_maximum')
    op.drop_column('analysis_results', 'tumblr_lower_quartile')
    op.drop_column('analysis_results', 'tumblr_average')
    op.drop_column('analysis_results', 'reddit_upper_quartile')
    op.drop_column('analysis_results', 'reddit_minimum')
    op.drop_column('analysis_results', 'reddit_median')
    op.drop_column('analysis_results', 'reddit_maximum')
    op.drop_column('analysis_results', 'reddit_lower_quartile')
    op.drop_column('analysis_results', 'reddit_average')
    # ### end Alembic commands ###
