"""empty message

Revision ID: ae57169933b6
Revises: 3d4cc03c273f
Create Date: 2021-03-22 13:46:51.266956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae57169933b6'
down_revision = '3d4cc03c273f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('reddit_analysis_complete', sa.Boolean(), nullable=False))
    op.add_column('analysis_results', sa.Column('tumblr_analysis_complete', sa.Boolean(), nullable=False))
    op.add_column('analysis_results', sa.Column('twitter_analysis_complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'twitter_analysis_complete')
    op.drop_column('analysis_results', 'tumblr_analysis_complete')
    op.drop_column('analysis_results', 'reddit_analysis_complete')
    # ### end Alembic commands ###
