"""empty message

Revision ID: c9280442d7be
Revises: 509f11d96ad9
Create Date: 2021-02-20 12:36:14.631471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9280442d7be'
down_revision = '509f11d96ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_twitter', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('text_twitter', sa.Column('is_analyzed', sa.Boolean(), nullable=False))
    op.add_column('text_twitter', sa.Column('text', sa.String(length=350), nullable=False))
    op.alter_column('text_twitter', 'analysis_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_twitter', 'analysis_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('text_twitter', 'text')
    op.drop_column('text_twitter', 'is_analyzed')
    op.drop_column('text_twitter', 'created_at')
    # ### end Alembic commands ###
